### ISSUE TITLE
add option to specify margin for safety

### ISSUE THREAD

**Issue by tinect** [MelvinAchterhuis/MelvAutoExchangeRates#1]
While shops work with foreign currencies, they like to specify a margin by percentage for all currencies. This could help to save money exchanges.

**Comment by MelvinAchterhuis** [comment]
I've released an update

![image](https://user-images.githubusercontent.com/26538915/191811175-bfd359d3-45b3-4619-a6d1-c4b718a3db42.png)

![image](https://user-images.githubusercontent.com/26538915/191811323-21ec67bb-7d03-4aa9-b3d1-d041c1b00256.png)

**Comment by tinect** [comment]
Great, thank you.
But shouldn't it be:
`$value *= (1 - $safetyMargin / 100);`
instead of `$value /= (1 + $safetyMargin / 100);`'?
🤔 
$value = 2;
$safetyMargin = 2;

Your calculation:  1,96078431372549
Correct would be: 1,96

**Comment by MelvinAchterhuis** [comment]
@tinect , adjusted
